parameters:
    #parameter_name: value

services:
    app.number.pattern.generator:
        class: AppBundle\Util\NumberPatternGenerator

    app.matrix.generator:
        class:  AppBundle\Util\MatrixGenerator
